### ISSUE TITLE
Lenster disconnected if you change Matic Chain

### ISSUE THREAD

**Issue by pucedoteth** [lensterxyz/lenster#3452] opened 2023-08-05 21:58 UTC
### Summary

I think this the most wanted feature to enable in Lenster. i hope you can add this feature to Lenster app so users can browse Lenster without need to connect to Matic Chain.

**Comment by bigint** [comment] 2023-08-08 08:14
Dupe of #1795

**Closed by bigint** 2023-08-08 08:14 UTC
