### ISSUE TITLE
about Dark mode

### ISSUE THREAD

**Issue by OHIRAH** [lensterxyz/lenster#1198] opened 2022-11-14 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dark mode is problem .  after changing Dark mode .  can not see ward(black)
![Screen Shot 2022-11-14 at 23 31 47](https://user-images.githubusercontent.com/90397620/201686622-b20e6743-123b-42cd-ba54-732298235552.jpg)
 so much . 

### Expected Behavior

white ward on Dark mode is better . like twitter .

### Steps To Reproduce

---

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

my  lens account . 
@ohira.lens

**Comment by foolo** [comment] 2022-11-22 13:24
@OHIRAH I'm trying to reproduce this. Does this problem still occur? For me it looks OK:
![Screenshot_2022-11-22_14-22-29](https://user-images.githubusercontent.com/667227/203324760-ffd44405-f736-4dd6-a2e7-31b8ef518f54.png)

**Comment by bigint** [comment] 2022-11-22 13:36
+1 I can't reproduce this 😕

**Comment by OHIRAH** [comment] 2022-11-23 01:08
Hi

My japanese friend’s lens is not problem .

Seems like only me .   
Yeah  maybe Browser extension . 
I imported several wallet …

I keep using daytime mode . 

Thanks .

**Comment by bigint** [comment] 2022-11-23 04:06
Closing this in favor of https://github.com/lensterxyz/lenster/issues/1253 🙇🏼

**Closed by bigint** 2022-11-23 04:06 UTC
Labels: needs review
