### ISSUE TITLE
I am trying to unfollow someone but its says "User rejected request"

### ISSUE THREAD

**Issue by jisharpmusic** [lensterxyz/lenster#1387] opened 2022-12-09 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I click unfollow and sign the request and then met with a "User rejected request" error

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by foolo** [comment] 2023-01-14 12:45
@jisharpmusic I can't reproduce this. Can you add some more info (for example, which wallet). Does it still occur?

**Comment by jisharpmusic** [comment] 2023-01-14 16:25
Hey there! Thanks for getting back to me - I reached out to them and they
had the option on lensfren changed so that follows werent open to the
public.
So perhaps a suggestion that the UI could change to reflect if somone
doesnt have follows open to the public. :)

cheers,
Ji Sharp

**Comment by foolo** [comment] 2023-01-14 16:36
@jisharpmusic Not sure I understand. This issue is about an error message "User rejected request" when trying to unfollow someone, right? I don't see the connection to whether or not follows are open to the public.

**Comment by jisharpmusic** [comment] 2023-01-14 16:42
ohhh damn. Sorry, I was responding back about a different issue. I sent another ticket to lenster about a different problem but I think that mightve been through discord now that I think about it. I sent this one a while ago so i forgot about it and replied through Gmail so I didnt see my initial message. Disregard that, and im pretty sure that I ended up resolving it. Eventually I was just able to unfollow.

**Comment by foolo** [comment] 2023-01-14 16:44
> Disregard that, and im pretty sure that I ended up resolving it. Eventually I was just able to unfollow.

No problem :) Thanks for confirming!
@bigint Seems like we can close this issue.

**Closed** 2023-02-28 14:22 UTC
Labels: needs review
