### ISSUE TITLE
Every time I log out and switch wallets, the website fails and login 

### ISSUE THREAD

**Issue by cryptopoplar** [lensterxyz/lenster#1809] opened 2023-02-15 13:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I log out and switch wallets, the website fails and login 

### Expected Behavior

Every time I log out and switch wallets, the website fails and login 

### Steps To Reproduce

Every time I log out and switch wallets, the website fails and login 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Every time I log out and switch wallets, the website fails and login [https://lenster.xyz/posts/0x017151-0xb5](url)

**Comment by bigint** [comment] 2023-02-28 14:03
Dupe of #1795

**Closed by bigint** 2023-02-28 14:03 UTC
Labels: needs review
