### ISSUE TITLE
duplicated posts

### ISSUE THREAD

**Issue by freelancingco7** [lensterxyz/lenster#2517] opened 2023-04-12 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I see duplicated posts in the explorer

### Expected Behavior

we need only one of each posts in the explorer

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by saagu335** [comment] 2023-04-12 15:04
Duplicate of #1031

**Closed by saagu335** 2023-04-12 15:04 UTC
