### ISSUE TITLE
My post was black!

### ISSUE THREAD

**Issue by lihanbok** [lensterxyz/lenster#1273] opened 2022-11-22 03:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Post was black!

### Expected Behavior

Picture was showed in my post!

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![report 1](https://user-images.githubusercontent.com/40301798/203211641-26d48fff-d8c8-43ac-82f2-2e665484e3c6.png)

**Comment by foolo** [comment] 2022-11-26 13:36
Looks like the same issue as #1048. For some reason there is a delay before uploaded images become available. 
For example, the post in the issue is now showing the image: https://lenster.xyz/posts/0x9a45-0x11

**Comment by bigint** [comment] 2022-11-28 03:19
Closing this as dupe of https://github.com/lensterxyz/lenster/issues/1048

I'll add detailed comments there 🙏🏼

**Closed by bigint** 2022-11-28 03:19 UTC
Labels: needs review
