### ISSUE TITLE
execution reverted

### ISSUE THREAD

**Issue by clemmietay** [lensterxyz/lenster#2821] opened 2023-05-06 16:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I post, it always fails with execution reversed

### Expected Behavior

everything is normal

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/131809035/236636534-a6dfcc29-b3e1-4be8-8b37-f69d96816602.png)

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment] 2023-05-07 11:31
Dupe of #2804

**Closed by bigint** 2023-05-07 11:31 UTC
